- hosts: localhost
  gather_facts: yes
  tasks:
    - name: generate an ssh key
      command: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
      args:
        creates: ~/.ssh/id_rsa
    - name: Downloading pub key
      fetch: src=~/.ssh/id_rsa.pub dest=/tmp/workstation_id_rsa.pub flat=yes fail_on_missing=yes
    - name: update apt
      apt: >
        update_cache=yes
        cache_valid_time=3600
      when: ansible_os_family == "Debian"
      sudo: yes

    - name: install deps (Ubuntu)
      apt: >
        pkg={{item}}
        state=installed
      with_items:
        - software-properties-common
        - python-pycurl
      when: ansible_os_family == "Debian"
      sudo: yes
    
    
    - name: add ppa repository
      apt_repository: repo="ppa:ansible/ansible"
      when: ansible_os_family == "Debian"
      sudo: yes
      ignore_errors: yes

    - name: install deps (Ubuntu)
      apt: >
        pkg={{item}}
        state=latest
      with_items:
        - git
        - ansible
        - ruby1.9.3
      when: ansible_os_family == "Debian"
      sudo: yes
    
    - name: install deps (RHEL)
      yum: >
        pkg={{item}}
        state=installed
      with_items:
        - git
        - ansible
      when: ansible_os_family == "RedHat"
      sudo: yes

    - name: install gem librarian
      gem: name={{item}} state=present user_install=no
      sudo: yes
      with_items:
         - librarian-ansible

    # not sure why these dependencies are not installing... (on debian, need to check ubuntu)
    - name: install gem librarian dependencies
      gem: name={{item}} state=present
      with_items:
         - librarian
         - thor
         - faraday
         - highline
         - multipart-post


    - name: git clone ansible-mesos-playbook
      #git: repo=https://github.com/fullergalway/ansible-mesos-playbook.git dest=~/ansible-mesos-playbook update=no 
      command: git clone https://github.com/fullergalway/ansible-mesos-playbook.git ansible-mesos-playbook
      args: 
        chdir: ~/
        creates: ansible_mesos_playbook

    - command: librarian-ansible install
      args: 
        chdir: ~/ansible-mesos-playbook/
        creates: librarian-roles

    - copy: src=templates/hosts.j2 dest=~/ansible-mesos-playbook/hosts
    - copy: src=templates/ansible.cfg.j2 dest=~/ansible-mesos-playbook/ansible.cfg

